version = 0.1
[default.deploy.parameters]
stack_name = "rss"
resolve_s3 = true
s3_prefix = "rss"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
confirm_changeset = true
