version = 0.1
[default.deploy.parameters]
stack_name = "sample1"
resolve_s3 = true
s3_prefix = "sample1"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
confirm_changeset = true
